AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront distribution for Smart Vehicle Maintenance frontend

Parameters:
  BucketName:
    Type: String
    Default: smart-vehicle-maintenance-frontend-495930420806
    Description: S3 bucket name for frontend

Resources:
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: !Sub '${BucketName}.s3-website-us-west-2.amazonaws.com'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
                - TLSv1.2
        Enabled: true
        DefaultRootObject: index.html
        Comment: Smart Vehicle Maintenance Frontend
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          MinTTL: 0
          DefaultTTL: 86400
          MaxTTL: 31536000
          Compress: true
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontURL:
    Description: CloudFront Distribution URL (HTTPS)
    Value: !GetAtt CloudFrontDistribution.DomainName
    Export:
      Name: smart-vehicle-maintenance-cloudfront-url
      
  CloudFrontDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref CloudFrontDistribution
    Export:
      Name: smart-vehicle-maintenance-cloudfront-id

