AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Smart Vehicle Maintenance & Service Scheduler

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: nodejs18.x
    Environment:
      Variables:
        VEHICLES_TABLE: !Ref VehiclesTable
        SERVICES_TABLE: !Ref ServicesTable
        USER_POOL_ID: !Ref UserPool

Parameters:
  ProjectName:
    Type: String
    Default: smart-vehicle-maintenance
    Description: Name of the project

Resources:
  # DynamoDB Tables
  VehiclesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-vehicles'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: vehicleId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: vehicleId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  ServicesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-services'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: vehicleId
          AttributeType: S
        - AttributeName: serviceId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
        - AttributeName: serviceDate
          AttributeType: S
      KeySchema:
        - AttributeName: vehicleId
          KeyType: HASH
        - AttributeName: serviceId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: serviceDate
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${ProjectName}-client'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH

  # Lambda Functions
  VehiclesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-vehicles'
      CodeUri: backend/functions/vehicles/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VehiclesTable
      Events:
        GetVehicles:
          Type: HttpApi
          Properties:
            Path: /vehicles
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        CreateVehicle:
          Type: HttpApi
          Properties:
            Path: /vehicles
            Method: POST
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        GetVehicle:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        UpdateVehicle:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}
            Method: PUT
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        DeleteVehicle:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}
            Method: DELETE
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer

  ServicesFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-services'
      CodeUri: backend/functions/services/
      Handler: index.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ServicesTable
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable
      Events:
        GetServices:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}/services
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        CreateService:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}/services
            Method: POST
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        UpdateService:
          Type: HttpApi
          Properties:
            Path: /services/{serviceId}
            Method: PUT
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer
        DeleteService:
          Type: HttpApi
          Properties:
            Path: /services/{serviceId}
            Method: DELETE
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer

  PredictionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-predictions'
      CodeUri: backend/functions/predictions/
      Handler: index.handler
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ServicesTable
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable
      Events:
        GetPredictions:
          Type: HttpApi
          Properties:
            Path: /vehicles/{vehicleId}/predictions
            Method: GET
            ApiId: !Ref HttpApiGateway
            Auth:
              Authorizer: CognitoJwtAuthorizer

  RemindersFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-reminders'
      CodeUri: backend/functions/reminders/
      Handler: index.handler
      Environment:
        Variables:
          SERVICES_TABLE: !Ref ServicesTable
          VEHICLES_TABLE: !Ref VehiclesTable
          REMINDERS_TOPIC_ARN: !Ref RemindersTopic
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ServicesTable
        - DynamoDBReadPolicy:
            TableName: !Ref VehiclesTable
        - SNSPublishMessagePolicy:
            TopicName: !Sub '${ProjectName}-reminders'
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)
            Input: '{}'

  # SNS Topic for Reminders
  RemindersTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${ProjectName}-reminders'
      DisplayName: Vehicle Service Reminders

  # API Gateway
  HttpApiGateway:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 300
      Auth:
        Authorizers:
          CognitoJwtAuthorizer:
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
              audience:
                - !Ref UserPoolClient
            IdentitySource: '$request.header.Authorization'
        DefaultAuthorizer: CognitoJwtAuthorizer
      # Note: SAM automatically handles OPTIONS without requiring auth

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApiGateway}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Sub '${ProjectName}-api-url'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${ProjectName}-user-pool-id'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${ProjectName}-user-pool-client-id'

  Region:
    Description: AWS Region
    Value: !Ref AWS::Region
    Export:
      Name: !Sub '${ProjectName}-region'

  VehiclesTableName:
    Description: Vehicles DynamoDB Table Name
    Value: !Ref VehiclesTable

  ServicesTableName:
    Description: Services DynamoDB Table Name
    Value: !Ref ServicesTable

